### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by Kuchiriel** [CoinAlpha/dsm#9]
This is a WebUI for hummingbot?

**Comment by mlguys** [comment]
No, it is a script to generate UI component for web builders.

**Comment by Kuchiriel** [comment]
Got it, thank you

**Comment by antoniobrandao** [comment]
Hi @Kuchiriel. This repo is a couple of things:

- The code that loads design tokens from the [HBUI Figma file](https://www.figma.com/file/hf03Mn2cecwA1ioUxlHg9P/Hummingbot-Design-System-1.3?type=design&node-id=306-4148&mode=design&t=7r1JxGgsiStuyxFh-0) to generate React components in Hummingbot style and generate the HBUI [NPM module](https://www.npmjs.com/package/@hummingbot/hbui)
- The code for the HBUI [documentation](https://hummingbot-ui.netlify.app/) site

If you want to use the HBUI design system in a React app you should use the NPM module. This NPM module not only has React components, but also design tokens and assets, which are useful to design apps using the Hummingbot style.

Alternative you can get started with one of the boilerplate projects:
[Next.js](https://github.com/hummingbot/hbui-boilerplate-nextjs)
[Gatsby](https://github.com/hummingbot/hbui-boilerplate-gatsby)
[Webpack](https://github.com/hummingbot/hbui-boilerplate-webpack)
[Webpack (TypeScript)](https://github.com/hummingbot/hbui-boilerplate-webpack-ts)
Let us know if you would like to see a boilerplate project with different specifications.

You can also get design material from the [Figma](https://www.figma.com/file/hf03Mn2cecwA1ioUxlHg9P/Hummingbot-Design-System-1.3?type=design&node-id=306-4148&mode=design&t=7r1JxGgsiStuyxFh-0) file to create your designs in Hummingbot style.
